### ISSUE TITLE
Add Apache 2.0 License to GoWrench Project

### ISSUE THREAD

**Issue by fernandoseguim** [guardiafinance/GoWrench#1]
# Objective  
Ensure the GoWrench project is properly licensed under **Apache 2.0** and that all future changes to the license file are **audited and reviewed**, according to Guardia's **Compliance by Design** principles.

---

# Deliverables

1. **Add Apache 2.0 License**
   - [x] Create a `LICENSE` file at the root of the repository with the official [Apache 2.0 text](https://www.apache.org/licenses/LICENSE-2.0.txt).
   - [x] Add a **"License"** section to the `README.md`:

     ```markdown
     ## License
     This project is licensed under the Apache License 2.0.  
     See the [LICENSE](./LICENSE) file for more information.
     ```

2. **Define CODEOWNERS for License Governance**
   - [x] Create a `.github/CODEOWNERS` file with the following entry:

     ```
     /LICENSE @ivanmds
     ```

3. **Enforce License Change Reviews via GitHub Actions**
   - [x] Add a workflow `.github/workflows/license-check.yml` with the following content:

     ```yaml
     name: License Check

     on:
       pull_request:
         types: [opened, synchronize, labeled, unlabeled]

     jobs:
       check-license:
         runs-on: ubuntu-latest
         steps:
           - name: Check for LICENSE file changes
             uses: dorny/paths-filter@v3
             id: changes
             with:
               filters: |
                 license:
                   - 'LICENSE'

           - name: Fail if LICENSE changed without legal-approved label
             if: steps.changes.outputs.license == 'true' && !contains(github.event.pull_request.labels.*.name, 'legal-approved')
             run: |
               echo "🚫 LICENSE file was changed but this PR is missing the 'legal-approved' label."
               exit 1
     ```

---

# Acceptance Criteria

- [x] `LICENSE` file exists and contains the full Apache 2.0 text.
- [x] `README.md` clearly references the license.
- [x] `.github/CODEOWNERS` is configured to require review from the appropriate approvers on license changes.
- [x] GitHub Action blocks PRs that modify `LICENSE` unless `legal-check` label is present.
- [x] All changes committed with signed commits and properly referenced in the PR.

---

# Reference

https://www.apache.org/licenses/LICENSE-2.0
